server:
  port: 8756

spring:
  application:
    name: eurka-client

#出错解决思路：https://blog.csdn.net/qq_32131937/article/details/87905262
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
