server:
  port: 8764

spring:
  application:
    name: service-ribbon

#\u51FA\u9519\u89E3\u51B3\u601D\u8DEF\uFF1Ahttps://blog.csdn.net/qq_32131937/article/details/87905262
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign.hystrix.enabled: true